### ISSUE TITLE
[auto-generated:fc1fda40] Type/State checking code smell

### ISSUE THREAD

**Issue by jb-error-reporter** [JetBrains-Research/IntelliJDeodorant#31]
- Plugin Name: IntelliJDeodorant
- Plugin Version: 1.0
- OS Name: Linux
- Java Version: 11.0.3
- Java VM Vendor: JetBrains s.r.o
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IC-192.6603.28
- App Version: 2019.2.2
- Last Action: null
- User's Permanent Installation ID: 1143e838-ea6f-484f-b383-0d17196e715f

```
java.lang.NullPointerException
	at core.ast.TypeCheckCodeFragmentAnalyzer.processTypeCheckCodeFragmentBranches(TypeCheckCodeFragmentAnalyzer.java:473)
	at core.ast.TypeCheckCodeFragmentAnalyzer.processTypeCheckCodeFragment(TypeCheckCodeFragmentAnalyzer.java:411)
	at core.ast.TypeCheckCodeFragmentAnalyzer.<init>(TypeCheckCodeFragmentAnalyzer.java:38)
	at core.ast.ClassObject.generateTypeCheckEliminations(ClassObject.java:136)
	at core.ast.SystemObject.generateTypeCheckEliminations(SystemObject.java:193)
	at core.ast.Standalone.getTypeCheckEliminationRefactoringOpportunities(Standalone.java:135)
	at ui.TypeCheckingPanel$1.lambda$run$1(TypeCheckingPanel.java:187)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at ui.TypeCheckingPanel$1.run(TypeCheckingPanel.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by lyubortk** [comment]
The problem cannot be reproduced on a correctly imported project.
