### ISSUE TITLE
[auto-generated:1e3cef7c] Worker exited due to exception

### ISSUE THREAD

**Issue by jb-error-reporter** [JetBrains-Research/IntelliJDeodorant#3654]
- Plugin Name: IntelliJDeodorant
- Plugin Version: 2020.3-1.0
- OS Name: Windows
- Java Version: 17.0.6
- Java VM Vendor: JetBrains s.r.o.
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IU-231.8109.175
- App Version: 2023.1
- Last Action: null
- User's Permanent Installation ID: ae94bab5-9819-4a07-b540-75dd2382a19e

```
java.lang.AssertionError: Registry key feature.usage.event.log.collect.and.upload is not defined
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.MissingResourceException: Registry key feature.usage.event.log.collect.and.upload is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:169)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:234)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:204)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:63)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:63)
	at org.jetbrains.research.intellijdeodorant.ide.fus.IntelliJDeodorantLoggerProvider.isRecordEnabled(IntelliJDeodorantLoggerProvider.java:18)
	at com.intellij.internal.statistic.eventLog.StatisticsEventLoggerProvider.getLogger(StatisticsEventLogger.kt:100)
	at org.jetbrains.research.intellijdeodorant.ide.fus.IntelliJDeodorantLogger.log(IntelliJDeodorantLogger.java:10)
	at org.jetbrains.research.intellijdeodorant.ide.fus.collectors.IntelliJDeodorantCounterCollector.trackRegistered(IntelliJDeodorantCounterCollector.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 8 more

```

**Comment by jb-error-reporter** [comment]
- Plugin Name: IntelliJDeodorant
- Plugin Version: 2020.3-1.0
- OS Name: Windows
- Java Version: 17.0.6
- Java VM Vendor: JetBrains s.r.o.
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IC-231.8109.175
- App Version: 2023.1
- Last Action: null
- User's Permanent Installation ID: dd955d61-c8af-4658-b4a8-7dfc7503b97e

```
java.lang.AssertionError: Registry key feature.usage.event.log.collect.and.upload is not defined
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.MissingResourceException: Registry key feature.usage.event.log.collect.and.upload is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:169)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:234)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:204)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:63)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:63)
	at org.jetbrains.research.intellijdeodorant.ide.fus.IntelliJDeodorantLoggerProvider.isRecordEnabled(IntelliJDeodorantLoggerProvider.java:18)
	at com.intellij.internal.statistic.eventLog.StatisticsEventLoggerProvider.getLogger(StatisticsEventLogger.kt:100)
	at org.jetbrains.research.intellijdeodorant.ide.fus.IntelliJDeodorantLogger.log(IntelliJDeodorantLogger.java:10)
	at org.jetbrains.research.intellijdeodorant.ide.fus.collectors.IntelliJDeodorantCounterCollector.trackRegistered(IntelliJDeodorantCounterCollector.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 8 more

```

**Comment by jb-error-reporter** [comment]
- Plugin Name: IntelliJDeodorant
- Plugin Version: 2020.3-1.0
- OS Name: Windows
- Java Version: 17.0.6
- Java VM Vendor: JetBrains s.r.o.
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IC-231.8109.175
- App Version: 2023.1
- Last Action: EmboldPlugin.Textboxes
- User's Permanent Installation ID: 07fe5d87-3615-4c2c-9a0b-48ef922aadfc

```
java.lang.AssertionError: Registry key feature.usage.event.log.collect.and.upload is not defined
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.MissingResourceException: Registry key feature.usage.event.log.collect.and.upload is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:169)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:234)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:204)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:63)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:63)
	at org.jetbrains.research.intellijdeodorant.ide.fus.IntelliJDeodorantLoggerProvider.isRecordEnabled(IntelliJDeodorantLoggerProvider.java:18)
	at com.intellij.internal.statistic.eventLog.StatisticsEventLoggerProvider.getLogger(StatisticsEventLogger.kt:100)
	at org.jetbrains.research.intellijdeodorant.ide.fus.IntelliJDeodorantLogger.log(IntelliJDeodorantLogger.java:10)
	at org.jetbrains.research.intellijdeodorant.ide.fus.collectors.IntelliJDeodorantCounterCollector.trackRegistered(IntelliJDeodorantCounterCollector.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 8 more

```
